# Generated by Django 3.2.12 on 2022-03-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productindex',
            name='custom_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
