# Generated by Django 3.2.12 on 2022-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220322_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes_options',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ProductSizesCustomField',
        ),
    ]
