# Generated by Django 3.2.12 on 2022-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220322_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes_options',
            new_name='available_colors',
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
