# Generated by Django 3.2.12 on 2022-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20220410_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='additional_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
