# Generated by Django 3.2.12 on 2022-03-06 20:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_productcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_carousel',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True),
        ),
    ]
