# Generated by Django 3.2.12 on 2022-03-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0002_megamenu_main_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megamenu',
            name='main_link',
        ),
        migrations.AddField(
            model_name='megamenu',
            name='mega_menu_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mega Menu Link'),
        ),
    ]
